"""baseline schema

Revision ID: 15ab2f3005b9
Revises: 
Create Date: 2026-02-23 22:24:33.338123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ab2f3005b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('price_basis', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('train_start_date', sa.Date(), nullable=False),
    sa.Column('train_end_date', sa.Date(), nullable=False),
    sa.Column('data_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_created_at'), 'forecast_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_runs_symbol'), 'forecast_runs', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'headline', 'published', name='uix_news_unique')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('interval', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_prices_timestamp'), 'stock_prices', ['timestamp'], unique=False)
    op.create_index('uq_symbol_timestamp_interval', 'stock_prices', ['symbol', 'timestamp', 'interval'], unique=True)
    op.create_table('forecast_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_intervals_forecast_run_id'), 'forecast_intervals', ['forecast_run_id'], unique=False)
    op.create_table('forecast_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_points_forecast_run_id'), 'forecast_points', ['forecast_run_id'], unique=False)
    op.create_table('forecast_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_scenarios_forecast_run_id'), 'forecast_scenarios', ['forecast_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_scenarios_forecast_run_id'), table_name='forecast_scenarios')
    op.drop_table('forecast_scenarios')
    op.drop_index(op.f('ix_forecast_points_forecast_run_id'), table_name='forecast_points')
    op.drop_table('forecast_points')
    op.drop_index(op.f('ix_forecast_intervals_forecast_run_id'), table_name='forecast_intervals')
    op.drop_table('forecast_intervals')
    op.drop_index('uq_symbol_timestamp_interval', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_timestamp'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_forecast_runs_symbol'), table_name='forecast_runs')
    op.drop_index(op.f('ix_forecast_runs_created_at'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
