"""add forecast window fields

Revision ID: 52acfe2a9dfd
Revises: 9e9e9db34dfa
Create Date: 2026-03-05 12:37:50.968763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52acfe2a9dfd'
down_revision: Union[str, Sequence[str], None] = '9e9e9db34dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_runs', sa.Column('forecast_from_date', sa.Date(), nullable=True))
    op.add_column('forecast_runs', sa.Column('forecast_to_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_runs', 'forecast_to_date')
    op.drop_column('forecast_runs', 'forecast_from_date')
    # ### end Alembic commands ###
