"""Add OHLCV fields and interval to StockPrice

Revision ID: 6a69a44da88a
Revises: 426102769b3d
Create Date: 2025-07-15 11:33:48.158267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a69a44da88a'
down_revision: Union[str, Sequence[str], None] = '426102769b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('open', sa.Float(), nullable=True))
    op.add_column('stock_prices', sa.Column('high', sa.Float(), nullable=True))
    op.add_column('stock_prices', sa.Column('low', sa.Float(), nullable=True))
    op.add_column('stock_prices', sa.Column('adj_close', sa.Float(), nullable=True))
    op.add_column('stock_prices', sa.Column('volume', sa.Integer(), nullable=True))
    op.add_column('stock_prices', sa.Column('interval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_prices', 'interval')
    op.drop_column('stock_prices', 'volume')
    op.drop_column('stock_prices', 'adj_close')
    op.drop_column('stock_prices', 'low')
    op.drop_column('stock_prices', 'high')
    op.drop_column('stock_prices', 'open')
    # ### end Alembic commands ###
