"""add forecast errors table

Revision ID: 9e9e9db34dfa
Revises: 15ab2f3005b9
Create Date: 2026-02-26 11:01:34.356668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9e9db34dfa'
down_revision: Union[str, Sequence[str], None] = '15ab2f3005b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_point_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('actual_price', sa.Float(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('abs_error', sa.Float(), nullable=False),
    sa.Column('pct_error', sa.Float(), nullable=True),
    sa.Column('within_interval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_point_id'], ['forecast_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_errors_forecast_point_id'), 'forecast_errors', ['forecast_point_id'], unique=False)
    op.create_index(op.f('ix_forecast_errors_symbol'), 'forecast_errors', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_errors_symbol'), table_name='forecast_errors')
    op.drop_index(op.f('ix_forecast_errors_forecast_point_id'), table_name='forecast_errors')
    op.drop_table('forecast_errors')
    # ### end Alembic commands ###
